apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:               # This RC will controll POD with given label
    app: myapp
  template:               # For POD creation , this RC will use this template.
    metadata:
      labels:
        app: myapp        # This label will be applicable on POD
    spec:
      containers:
      - name: con1
        image: nginx:latest
        ports:
        - containerPort: 80   # Port on the container itself
          protocol: TCP

